### ISSUE TITLE
[FEAT] Remove use of default_node_pool.node_taints 

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-aks-light#12]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `node_taints` has been deprecated an removed from AzureRM provider v3.86.0 as per 
- https://github.com/hashicorp/terraform-provider-azurerm/pull/24167

This module should be updated accordingly, unless there are reasons to not to.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by Shr3ps** [comment]
Thanks for this issue, do you think you may have time to open a PR?

**Comment by mloskot** [comment]
I'll try, next week.

**Comment by mloskot** [comment]
Apologies for delay, here it is #13
