### ISSUE TITLE
[BUG] Module cannot be found in the module registry at registry.terraform.io

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-aks-light#2]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.5

### AzureRM Provider Version

3.78.0

### Affected Resource(s)/Data Source(s)

n/a

### Terraform Configuration Files

```hcl
// Based on https://github.com/claranet/terraform-azurerm-aks-light/blob/ca2f620ac9f08b5a44e9deabdf188eb3deff9489/README.md

module "aks" {
  source  = "claranet/aks-light/azurerm"
  version = "7.0.0" # https://github.com/claranet/terraform-azurerm-aks-light/blob/ddc8b23f06e60757d4e5bb87db441a19640aee4d/VERSION

  // ...
}
```

### Debug Output/Panic Output

```shell
...
Downloading registry.terraform.io/claranet/regions/azurerm 7.0.0 for azure_region...
- azure_region in .terraform/modules/azure_region
Downloading registry.terraform.io/claranet/keyvault/azurerm 7.5.0 for keyvault...
- keyvault in .terraform/modules/keyvault
Downloading registry.terraform.io/claranet/diagnostic-settings/azurerm 6.5.0 for keyvault.diagnostics...
- keyvault.diagnostics in .terraform/modules/keyvault.diagnostics
- remote_state_stack_terraform in ../../../../../modules/cadcorp/terraform-azurerm-remote-state
Downloading registry.terraform.io/claranet/rg/azurerm 6.1.0 for resource_group...
- resource_group in .terraform/modules/resource_group
╷
│ Error: Module not found
│
│   on r-aks.tf line 1:
│    1: module "aks" {
│
│ Module "aks" (from r-aks.tf:1) cannot be found in the module registry at registry.terraform.io.
╵

Error: running "terraform init
```

### Expected Behaviour

I'd expect the `module "aks"` example from the current [README.md](https://github.com/claranet/terraform-azurerm-aks-light/blob/ca2f620ac9f08b5a44e9deabdf188eb3deff9489/README.md) to work.

### Actual Behaviour

See the "Debug Output/Panic Output" section.

### Steps to Reproduce

1. Copy the usage example
2. Run `terraform init`

### Important Factoids

The registry only lists the [`aks` module superseded by `aks-light`](https://github.com/claranet/terraform-azurerm-aks-light#why-replacing-the-previous-claranet-aks-module).

![image](https://github.com/claranet/terraform-azurerm-aks-light/assets/80741/d12e75ee-d44c-4b4e-84f6-911355b40a96)

**Comment by Shr3ps** [comment]
Don't know why, it was not on the registry indeed.
I published it again: https://registry.terraform.io/modules/claranet/aks-light/azurerm/latest

**Comment by mloskot** [comment]
@Shr3ps  Awesome, thank you!
