### ISSUE TITLE
[FEAT] Make oms_agent optional

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-aks-light#4]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#oms_agent says the block is optional, so it would be useful if user of this module can omit it as well.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by jmapro** [comment]
Hello !

You may be able to disable it by passing `oms_agent = null`

**Comment by mloskot** [comment]
Thanks!
