### ISSUE TITLE
[BUG] AcrPull role assigned to control plane managed identity instead of kubelet identity

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-aks-light#7]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.6.5

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
module "aks" {
  source  = "claranet/aks-light/azurerm"
  version = "~> 7.0.1"
  ...
  container_registries_ids = [
    var.custom_acr_id
  ]
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

After https://learn.microsoft.com/en-us/azure/aks/use-managed-identity, it is `<cluster>-agentpool` identity that needs the `AcrRole` to access a private ACR:

![image](https://github.com/claranet/terraform-azurerm-aks-light/assets/80741/856d3268-bbc3-4dc3-a624-e4081e3ffc00)

That is also confirmed by https://learn.microsoft.com/en-us/azure/aks/cluster-container-registry-integration

> The AKS to ACR integration assigns the [AcrPull role](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#acrpull) to the [Microsoft Entra ID managed identity](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) associated with the **agent pool** in your AKS cluster

There is another article https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/cannot-pull-image-from-acr-to-aks-cluster but it uses an ambiguous expression _"identity that's associated with the AKS cluster"_  which should be clarified that it is not the actual AKS cluster (control plane) identity but identity associated with the agent pool, in fact, kubelet identity as it is better explained in the two articles referenced above.

### Actual Behaviour

https://github.com/claranet/terraform-azurerm-aks-light/blob/c3c948baaffe19187bbb518338bca12d38c30e14/r-rbac.tf#L26-L32

### Steps to Reproduce

1. Create the cluster using this node
2. Try to deploy Pod which references image from the ACR passed via `var.custom_acr_id` above
    
    ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: myapp
    spec:
      containers:
      - name: myapp
        image: myregistry.azurecr.io/myapp/alpine:1.2.3
    ```
3. Observe `ImagePullBackOff` errors
4. Replace the role assignment in https://github.com/claranet/terraform-azurerm-aks-light/blob/c3c948baaffe19187bbb518338bca12d38c30e14/r-rbac.tf#L26-L32 with `AcrPull` assignment to the kubelet identity
    ```
    # Allow Kubelet Identity to authenticate with Azure Container Registry (ACR)
    resource "azurerm_role_assignment" "aks_kubelet_uai_acr_pull" {
      for_each = toset(var.container_registries_ids)
    
      scope                = each.key
      principal_id         = azurerm_kubernetes_cluster.aks.kubelet_identity[0].object_id
      role_definition_name = "AcrPull"
    }
    ```
5. After a few minutes, observe the cluster self-healing and being able to pulling the image from the ACR and complete deployment of the pod.

### References

- @jmapro forgive me calling you out, but I've just discovered this issue and it turns out it is a show stopper for those using private ACR-s and since the fix is trivial it may be worth checking it in for this week release.

**Comment by jmapro** [comment]
Hello ! 

I need to check why we use the User Assigned Identity instead of the Kubelet system assigned identity. Most of the time, we use User Assigned Identity to avoid dependencies issues with Terraform.

**Comment by mloskot** [comment]
@jmapro I see. For my simple needs, I usually do the other way around, let AKS to use the System Assigned Identity, then I ask for it with `data "azurerm_user_assigned_identity"` and assign it roles. 

>  then improve the code by creating a specific Identity for the Kubelet.

Yes, this would be useful indeed.
